postgres_password: ENC[AES256_GCM,data:mNuStC8ccmhVJcEizMPLFt0WrHI3OBbHcgVOYr9nkv3FXVJSLcVR+yKoh/LOOad2,iv:nj2u/6L6VpNNMX1feNE7o9u/NddQC42prjHVu8lBTvg=,tag:PCzT4DUABZNXVA/r5vJz4g==,type:str]
redis_password: ENC[AES256_GCM,data:OgsRNQAepnAmMXdy2v692mSmZEYeXFuPsPmkBkjyFSRTrYmmzi3UYRXXdW/WsRX4,iv:URKLbqrS7V466rI/7tfaSrQfl0z/m1jRGgalDTvMie0=,tag:cYby5dVa9cySHIjqF57X/A==,type:str]
jwt_secret: ENC[AES256_GCM,data:1Yi4Fum/qY5x7zSHEhj517LtqHl3sfaANzop/kDZzBB+iOTIJgtsuRGEcJ/h7kSI5cPAN/3xtHnyaMwZV6tNUg==,iv:+SVzqRsLCtB73H1/SU9w1mP5tDpQrBhlhg+XmmGQiCo=,tag:qzIRIszuETMmy8XzkkoBCw==,type:str]
refresh_token_secret: ENC[AES256_GCM,data:HpGVwLi/8ftyH3XNUs4KMv1w6GWr+oRJ+nN7L8yC+YFZ+cmCgB+Us9pfMm0AbiQZP2jOu5n74bHwFxkREUT8IQ==,iv:3ZMNFV310QFkfBOimZ5i1eBpqsXpoPsamOwocmImslw=,tag:KDPPA4EnxnDBe3TuDAcZpA==,type:str]
captcha_secret: ENC[AES256_GCM,data:/pjkECeiE0JJ+8V0x+vMrlF8ztJvM8hXcRVbpwy6W8xtjFCwTbZz+umqbwgxmBI5GtUJ6BlY3tLFv+cMNSN0JQ==,iv:OomrgV8HD7HBZZDudx7wklAe8zF8MfwU8mLep3hwkPY=,tag:SsfWWuyNcMU3IzzW3HRo5A==,type:str]
reaper_password: ENC[AES256_GCM,data:l1S8YL8GUbgsEh1w7rbhEV51G89RYPzGJFOFGPSy041bRzDWiLW34JhXQi7RO17Q,iv:cLAHsO2iDntfUXYQfPvHv/WXkTG8S5jtW8byVcKtS30=,tag:cDm/csx8QTVB9rlH1IVi5Q==,type:str]
grafana_admin_password: ENC[AES256_GCM,data:GY9chPNCPldjhMpzYdIA/xvq/PoN3+/1VHHjIAz2Ee8=,iv:V+5hvmJpYftrcFaIbQgMys8wxNMLTpIGUp/GSdISVJU=,tag:IC+T9sLIeUYqWnpYF0ibhA==,type:str]
alert_webhook_url: ENC[AES256_GCM,data:p8uxnrDYvAknOVe4QAVUJm1lY6//WSkmKglJDG5l6vouAR/XRHDw,iv:qCXiUbFDSpDoadQ2fvW+s/uzeYZs/toVFtrQHU/Lfzw=,tag:/cx/BTNjl+mzxReKpGHaBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSW1tUnFIcUMyaGM2NVJU
            b2Z2VEprRlByalZtSXRoNDZ4eXV4dk1URlYwCkFGbGF6MG9wcjkybFkzOGJEbUl2
            L01xY01SWHM0UUlpc3k2Q2tJWW50QVUKLS0tIFpoNEJhNm5GclRqTnFNMStqR1d0
            MUt2RkJFL09VQ3l2RXR0NWF6S1JULzgKj4fNXe5/h8QFUe3Ud3S9GW7TSYhVmNO/
            TGERQRZrQIabyihVtWUEv4+PhZfgifkA11IQs+020+6ifzz2ipRwJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g0yn0akuh9x3msxeyhuhakc6njfa290mmzwvxdc0dpnly47mhdlqec0vya
    lastmodified: "2026-07-29T15:14:56Z"
    mac: ENC[AES256_GCM,data:exSvaKTK/IYP2WGfOhNhECMkC0oyjNz1T3iLIj3L+9yDxeqnaMPXcJ9FF1ppcdcVNheuhCox8BVjWCAXOmSqxpXTa5D+HIKinC7Txc9eZErBpjKuwAkmoa4JKRIms3UMXlB3LP5mL/+hCQbF17hGtz10smVjvmZecgorlSjmJEo=,iv:eUKYa0krrTn+qM9FrCDpAR98pkRC3YjNEtq28RqhvvI=,tag:OUbu34tWhoCPiltzVVGbTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
