postgres_password: ENC[AES256_GCM,data:7HU4HrsUSi764+rTFYFOSSuCuY9d++HCMzc+oeGzokB3M2+2w4COYQdGzCeRFDCE,iv:I/7SdbFIlHW96NC1FhkEeoBIiZiMg4h3gEydFL3TvgE=,tag:pF3/pk+AEENYPFis9hO3tg==,type:str]
redis_password: ENC[AES256_GCM,data:1Mmq4lXpB8Kq2QOdC4yw+2/KkB3TcYDUjONtdHx2xAXToqfEH4e8WoqeVJKzradY,iv:QeECXttLGBiAklyxnzlkt79mB6rWdKhaSKNocBNvIoY=,tag:PsLLLjHcz0XcIEVaSqOGSA==,type:str]
jwt_secret: ENC[AES256_GCM,data:iCTKJdCQ46VK/ceSBtkm+aJ9iZirmZNT3ixooiPqZoWjS2Yo0z1dEuriRTT8YhafcCZXf92+YElFGgudeXHlhw==,iv:Mt8JXQmEgOeXHUS/E8qjyijNzCdo770BTifHoH240/o=,tag:w5KbS9Vdl/3qsXyD/1h1oA==,type:str]
refresh_token_secret: ENC[AES256_GCM,data:lx7krpc9wLeNC4hNFnq+gLbIWWwIyexmhx2FQhReJ8IR7r6GzAfxrqV8e9zdst22n/TmqspbbniEtp3OnVBXMw==,iv:vB9qRljvhQdfr54A8DveoklzOh5i/Rt9795ZU5MKw6E=,tag:J4G11lk50BS/nkmbJ7HEvw==,type:str]
captcha_secret: ENC[AES256_GCM,data:n/s/oW0h4BTDjA0zBmy5O1GlQ41N6/7NVbbZeRKUilvVRYfDAPOAnUY4sqgBt723ESAviVXXSYgxOos8jvMImQ==,iv:t9pmf/3DKarouZJ0eQq8bqV6FiNhM+pxPVZTWBqxqqQ=,tag:bNoJBJuE+P7YewerNxHf5g==,type:str]
reaper_password: ENC[AES256_GCM,data:g5PDxGJXz7DlwBjmgFLIobLQ4sHSxYeo6rt22glQJDdnzWq1x6M+zZI/vVllbZz4,iv:fDXA8XLFj1po/H2xiIa4ClihKN1dgLGRYbTdlgjPDa0=,tag:Tz77PnUvf+CoxcqLGCD2MQ==,type:str]
grafana_admin_password: ENC[AES256_GCM,data:G+rEgQk8aT41QeFLQPzVCRaDASZaauO8a1WyOMZF0Zg=,iv:cEBPqBOHy2EjLeKlaxc24QYtoS/bV9xhY1yT2W9BDq8=,tag:C6FBIR0edmt8kHKtb0SIbQ==,type:str]
alert_webhook_url: ENC[AES256_GCM,data:z2iwo7Pd6JHZHxFlDWj5IEupq3FBa2dISp99Eh79E74/gjtI/epV,iv:qCXiUbFDSpDoadQ2fvW+s/uzeYZs/toVFtrQHU/Lfzw=,tag:ch+keHsU8DdB+Zr4beER+w==,type:str]
smtp_password: ENC[AES256_GCM,data:s3HnGRRVlen0FI7Ngvyi4rhYuaiCq9fx5j2J4/tZHHE=,iv:I2/4RuQ/LtFRbuuqNJZcIO66lyyj/vNUIzP0RMPNA1k=,tag:vX3cSUOLsZPB6sjbNE8bgw==,type:str]
email_verify_secret: ENC[AES256_GCM,data:5PrmBaOU7eNAHu4wrVGInNYaLHJSECKa6T4CcqQ1/s0H5/sRV3GhH9AzcpcNHeG/xS6zxsnX9cDd2vg8swZ2FA==,iv:4CFgwklD6piFF5JrzmLL6ui/ZrNUfD2sFo3NYkUxEfY=,tag:QoyuCvRMWAj6ffOmP0HGWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbGJ2Sm1KNCs5RWpZZEVO
            am11YTBDem5OOFVJbzJtaWlCUHFjR2pDQlRFCmlaQkpadGNITEZRdzdJd1Frc2JJ
            WDlXMmNDZ2FJdjl5YjByakNqTE44YTgKLS0tIHcxc1Yyc2pDR2x4aDNTcU85Qzhy
            bkRJREhNMU9aV0RRL3FuM3NJTlZBQnMKE9mm2oYnquMzdKxmUWCagT+NCJszl8qW
            HpHgl3ROG3SoRC1DPfMv+Ff8XJJi+gNN8ZLoJGGmJi21xmRJiYGvPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d9guthsymfhw4p2z3xepgxcktn7626vvcy30rt920wdeg0gx494qgwum2n
    lastmodified: "2026-07-31T16:40:41Z"
    mac: ENC[AES256_GCM,data:vJNn2tS7cN68WE1rQgx0Isi3swvUN6LXwUjhq7hhwWg5QY6Vu/XA1nQnpLvbQWetLAfCaC5xP5wWQnis0C8lNgqRD2JHf5qXknZtBuGDQQDCBi4uMpihfUNEyQyleqSCp5pYiKPswpdbIGf636GG9fVpoe1oL/ZPKYLhkR6kycg=,iv:365lHLBGXm08hqkuLQtq67jz6IczZVitXZ1cKzVSM9A=,tag:ogCfA4N+w5PO/UzzNNRBbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
